import fs from "fs";
import path from "path";
import {
  createSubmissionClient,
  createKafkaClient,
  createConsumer,
  TOPICS,
  SubmissionResultEventSchema,
  toProtoLanguage,
  VerdictType,
} from "@bytearena/shared";
import type { CreateSubmissionResponse } from "@bytearena/shared/generated/bytearena/v1/CreateSubmissionResponse";

interface TestCaseSpec {
  name: string;
  file: string;
  expectedVerdict: VerdictType;
}

const CASES: TestCaseSpec[] = [
  {
    name: "Correct solution (ok.py)",
    file: "scripts/fixtures/sum-two/ok.py",
    expectedVerdict: "ACCEPTED",
  },
  {
    name: "Wrong answer (wrong.py)",
    file: "scripts/fixtures/sum-two/wrong.py",
    expectedVerdict: "WRONG_ANSWER",
  },
  {
    name: "Infinite loop (infinite.py)",
    file: "scripts/fixtures/sum-two/infinite.py",
    expectedVerdict: "TIME_LIMIT_EXCEEDED",
  },
  {
    name: "Runtime error (runtime_error.py)",
    file: "scripts/fixtures/sum-two/runtime_error.py",
    expectedVerdict: "RUNTIME_ERROR",
  },
];

async function main(): Promise<void> {
  console.log("=== ByteArena Smoke Test ===");

  const grpcAddr = process.env.SUBMISSION_GRPC_ADDR || "localhost:50051";
  const submissionClient = createSubmissionClient(grpcAddr);

  // Set up Kafka consumer to observe submissions.results
  const kafka = createKafkaClient(`smoke-verifier-${Date.now()}`);
  const consumer = await createConsumer(kafka, {
    groupId: `smoke-verifier-group-${Date.now()}`,
    sessionTimeout: 15000,
  });

  await consumer.subscribe({
    topic: TOPICS.SUBMISSIONS_RESULTS,
    fromBeginning: false, // only capture results generated by this smoke test
  });

  const submissionResults = new Map<
    string,
    {
      spec: TestCaseSpec;
      started: boolean;
      totalTests: number;
      testResults: { index: number; verdict: VerdictType }[];
      finalVerdict?: VerdictType;
    }
  >();

  // Start consumer message handler
  const allFinalPromise = new Promise<void>((resolve, reject) => {
    const timeout = setTimeout(() => {
      reject(new Error("Timeout waiting for all submissions to be judged"));
    }, 90000); // 90 seconds timeout

    consumer.run({
      autoCommit: true,
      eachMessage: async ({ message }) => {
        const raw = message.value?.toString("utf8");
        if (!raw) return;

        try {
          const parsed = SubmissionResultEventSchema.parse(JSON.parse(raw));
          const sub = submissionResults.get(parsed.submissionId);
          if (!sub) return; // not from this test run

          if (parsed.type === "JUDGING_STARTED") {
            sub.started = true;
            sub.totalTests = parsed.totalTests;
            console.log(
              `[RESULT] [${sub.spec.name}] JUDGING_STARTED: totalTests=${parsed.totalTests}`
            );
          } else if (parsed.type === "TEST_RESULT") {
            sub.testResults.push({
              index: parsed.testIndex,
              verdict: parsed.verdict,
            });
            console.log(
              `[RESULT] [${sub.spec.name}] TEST_RESULT: testIndex=${parsed.testIndex} verdict=${parsed.verdict} (${parsed.timeMs}ms)`
            );
          } else if (parsed.type === "FINAL_VERDICT") {
            sub.finalVerdict = parsed.verdict;
            console.log(
              `[RESULT] [${sub.spec.name}] FINAL_VERDICT: ${parsed.verdict} (expected: ${sub.spec.expectedVerdict})`
            );

            // Check if all submitted cases have reached final verdict
            const allFinished = Array.from(submissionResults.values()).every(
              (s) => s.finalVerdict !== undefined
            );
            if (allFinished) {
              clearTimeout(timeout);
              resolve();
            }
          }
        } catch (err) {
          console.error("Error parsing result event:", err);
        }
      },
    });
  });

  // Give consumer 2 seconds to join group and be ready
  console.log("Waiting for Kafka results consumer to connect...");
  await new Promise((r) => setTimeout(r, 2000));

  // Submit each test solution
  console.log("\nSubmitting solutions via gRPC CreateSubmission...");
  for (const tc of CASES) {
    const code = fs.readFileSync(path.resolve(tc.file), "utf8");

    const response = await new Promise<CreateSubmissionResponse>(
      (resolve, reject) => {
        submissionClient.createSubmission(
          {
            problemId: "sum-two",
            language: toProtoLanguage("PYTHON"),
            code,
            handle: "smoke-tester",
          },
          (err, res) => {
            if (err) return reject(err);
            resolve(res!);
          }
        );
      }
    );

    const subId = response.submission!.id!;
    submissionResults.set(subId, {
      spec: tc,
      started: false,
      totalTests: 0,
      testResults: [],
    });

    console.log(`Submitted [${tc.name}]: submissionId=${subId}`);
  }

  console.log("\nWaiting for live judging results stream from Kafka...");
  await allFinalPromise;

  // Disconnect consumer
  await consumer.disconnect();

  // Validate all results
  console.log("\n=== Verifying All Verdicts ===");
  let failed = false;
  for (const [subId, data] of submissionResults.entries()) {
    console.log(`\nCase: ${data.spec.name} (${subId})`);
    console.log(`- Started: ${data.started} (totalTests=${data.totalTests})`);
    console.log(`- Test results count: ${data.testResults.length}/5`);
    console.log(`- Final verdict: ${data.finalVerdict}`);
    console.log(`- Expected verdict: ${data.spec.expectedVerdict}`);

    if (!data.started) {
      console.error(`FAIL: JUDGING_STARTED event missing for ${data.spec.name}`);
      failed = true;
    }
    if (data.testResults.length !== 5) {
      console.error(
        `FAIL: Expected 5 test results, got ${data.testResults.length} for ${data.spec.name}`
      );
      failed = true;
    }
    if (data.finalVerdict !== data.spec.expectedVerdict) {
      console.error(
        `FAIL: Verdict mismatch for ${data.spec.name}. Expected ${data.spec.expectedVerdict}, got ${data.finalVerdict}`
      );
      failed = true;
    }
  }

  if (failed) {
    console.error("\n❌ Smoke test FAILED!");
    process.exit(1);
  }

  console.log("\n✅ All 4 submissions judged with correct verdicts and test streams!");
}

main().catch((err) => {
  console.error("Fatal smoke test error:", err);
  process.exit(1);
});
